export { Hero } from './Hero'
export { About } from './About'
export { AboutKiosk } from './AboutKiosk'
export { Features } from './Features'
export { ContactCTA } from './ContactCTA'
export { JayaGrocers } from './JayaGrocers'
export { BreezeCollab } from './BreezeCollab'
export { PartnershipsGallery } from './PartnershipsGallery'
